#!/usr/bin/env node
/**
 * new-portal.mjs — the ONE way to create a new ASG client portal.
 *
 * Rex 2.0 guardrail (2026-09-04): every prior portal was hand-copied from
 * an existing config block, which is exactly how andrew/ryanh/shield-caleb
 * ended up duplicated across two files, how rbp-ken drifted to the wrong
 * agent label, and how gnoles nearly shipped broken. This script is the
 * fix: one command, one canonical schema, no copy-paste.
 *
 * Usage:
 *   node scripts/new-portal.mjs --slug=acme-jane --client="Jane Smith" \
 *     --company="Acme Corp" --pin=8421 [--agent=rex] [--logo=https://...]
 *
 * Defaults:
 *   agent   = kit (steel blue #4A7FA5)   — pass --agent=rex for Shield (green #4ADE80)
 *   pin     = random 4-digit if omitted
 *   modules = ['welcome', 'chat', 'documents']
 *
 * Refuses to run if the slug already exists anywhere in the config registry
 * — this is what makes duplicate configs structurally impossible going forward.
 */
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CONFIG_PATH = path.join(__dirname, '../src/src/config/shield-portal-configs.ts');

const KIT_ACCENT = '#4A7FA5';
const REX_ACCENT = '#4ADE80';

function parseArgs() {
  const args = {};
  for (const arg of process.argv.slice(2)) {
    const m = arg.match(/^--([a-zA-Z]+)=(.*)$/);
    if (m) args[m[1]] = m[2];
  }
  return args;
}

function fail(msg) {
  console.error(`\n❌  ${msg}\n`);
  process.exit(1);
}

function randomPin() {
  return String(Math.floor(1000 + Math.random() * 9000));
}

function toConstName(slug) {
  return slug.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase() + '_CONFIG';
}

const args = parseArgs();

// ── Validate required args ───────────────────────────────────────────────
if (!args.slug) fail('Missing --slug=<slug> (e.g. --slug=acme-jane)');
if (!args.client) fail('Missing --client="Full Name"');
if (!args.company) fail('Missing --company="Company Name"');

if (!/^[a-z0-9-]+$/.test(args.slug)) {
  fail(`Invalid slug "${args.slug}" — lowercase letters, numbers, and hyphens only.`);
}

const agent = (args.agent || 'kit').toLowerCase();
if (agent !== 'kit' && agent !== 'rex') {
  fail(`Invalid --agent="${args.agent}" — must be "kit" or "rex". Rex is reserved for Shield Technologies portals only.`);
}

const pin = args.pin || randomPin();
if (!/^\d{4}$/.test(pin)) fail(`Invalid --pin="${args.pin}" — must be exactly 4 digits.`);

const agentLabel = agent === 'rex' ? 'Rex' : 'Kit';
const accentColor = agent === 'rex' ? REX_ACCENT : KIT_ACCENT;
const constName = toConstName(args.slug);
const [firstName] = args.client.split(' ');

// ── Guardrail: refuse duplicate slugs across BOTH config files ──────────
const PORTAL_CONFIGS_PATH = path.join(__dirname, '../src/src/config/portal-configs.ts');
const existingSlugs = new Set();

for (const filePath of [CONFIG_PATH, PORTAL_CONFIGS_PATH]) {
  if (!existsSync(filePath)) continue;
  const content = readFileSync(filePath, 'utf8');
  const matches = content.matchAll(/slug:\s*'([^']+)'/g);
  for (const m of matches) existingSlugs.add(m[1]);
}

if (existingSlugs.has(args.slug)) {
  fail(`Slug "${args.slug}" already exists. Pick a different slug — duplicate configs are exactly what Rex 2.0 fixed. Check both portal-configs.ts and shield-portal-configs.ts before choosing a name.`);
}

// ── Generate the config block (canonical ASGPortalBase / PortalConfig schema) ──
const block = `
// ─── ${firstName.toUpperCase()} — ${args.company} / ${agentLabel} ─────────────────────────────────
// clients.axiomstreamgroup.com/${args.slug}
// ${args.client} — ${args.company}. ${agentLabel} agent, ${agent === 'rex' ? 'green' : 'steel blue'} accent.
// Generated by scripts/new-portal.mjs on ${new Date().toISOString().slice(0, 10)} — do not hand-edit the schema shape.
export const ${constName}: PortalConfig = {
  slug: '${args.slug}',
  pin: '${pin}',
  clientName: '${args.client}',
  company: '${args.company}',
  memberName: '${firstName}',
  agentLabel: '${agentLabel}',
  agentId: '${agent}',
  accentColor: '${accentColor}',
  themeMode: 'dark',
  ${args.logo ? `logoUrl: '${args.logo}',\n  ` : ''}tagline:
    "Private access to ${agentLabel} — your ${args.company} AI, pre-loaded with your " +
    "context. Every conversation starts from there.",
  whatWeKnow: [
    { label: 'Contact', value: '${args.client}' },
    { label: 'Company', value: '${args.company}' },
  ],
  poweredBy: 'AxiomStream Group · ${agentLabel}',

  intakeLabel: 'My Context — 2 Minutes',
  intakeTitle: 'Load Your Context',
  intakeSubtitle: 'Give ${agentLabel} your priorities. Takes 2 minutes. Every conversation after this starts smarter.',

  chat: {
    transport: 'api-proxy',
    placeholder: 'Ask ${agentLabel} anything…',
    greeting: (savedContext) =>
      savedContext
        ? "${firstName} — ${agentLabel} here, context loaded. What are we working on?"
        : "Hey ${firstName}. ${agentLabel} here. Drop into My Context to load your priorities, or just ask me anything now.",
    apiEndpoint: '/api/chat',
    historyEndpoint: '/api/history',
    persistEndpoint: '/api/portal-chat-history',
  },

  intakeFields: [
    {
      key: 'topPriority',
      label: 'What is your top priority right now?',
      type: 'textarea',
      placeholder: 'What you want ${agentLabel} to help with most...',
    },
    {
      key: 'notes',
      label: 'Anything else ${agentLabel} should know?',
      type: 'textarea',
      placeholder: 'Context, background, current projects...',
    },
  ],

  modules: ['welcome', 'chat', 'documents'],

  moduleOptions: {
    documents: {
      tenantId: '${args.slug}',
      description: 'Upload documents you want ${agentLabel} to reference in conversations.',
    },
  },
};
`;

// ── Append to shield-portal-configs.ts (canonical ASGPortalBase schema file) ──
const currentContent = readFileSync(CONFIG_PATH, 'utf8');
const updatedContent = currentContent.trimEnd() + '\n' + block;
writeFileSync(CONFIG_PATH, updatedContent, 'utf8');

// ── Report the manual step still required (route registration) ─────────
console.log(`
✅  Portal config created: ${constName}
    File: src/src/config/shield-portal-configs.ts
    Slug: /${args.slug}
    PIN:  ${pin}
    Agent: ${agentLabel} (${accentColor})

⚠️  ONE MANUAL STEP REMAINING — add the route in src/src/main.tsx:

    1. Add to the import line:
       import { ..., ${constName} } from './config/shield-portal-configs'

    2. Add a route (near the other ${agentLabel === 'Rex' ? 'Shield' : 'Kit'} portals):
       <Route path="/${args.slug}" element={<ASGPortalBase config={${constName}} />} />

Then: npm run build && git add -A && git commit -m "Add ${args.slug} portal" && git push
`);
